# Generated by Django 3.1.5 on 2021-01-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod_video', '0002_auto_20210115_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
