# Generated by Django 3.1.5 on 2021-01-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vod_video', '0006_auto_20210120_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
