# Generated by Django 3.1.5 on 2021-01-20 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vod_video', '0007_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofiles',
            name='dislikes',
            field=models.ManyToManyField(related_name='video_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videofiles',
            name='likes',
            field=models.ManyToManyField(related_name='video_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
